spring:
  # Cấu hình data source cho môi trường local
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  # Cấu hình JPA cho môi trường local
  jpa:
    hibernate:
      ddl-auto: validate # Validate khi có flyway
    show-sql: true # Hiển thị câu lệnh SQL trong log để tối ưu khi cần
    properties:
      hibernate:
        format_sql: true # Định dạng câu lệnh SQL cho dễ đọc

  # Cấu hình tự động hỗ trợ docker khi chạy ứng dụng local
  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop # Tự động khởi động và dừng Docker Compose khi ứng dụng chạy và dừng
      file: docker/local/compose.yaml # Đường dẫn đến file Docker Compose cho môi trường local (tính từ thư mục gốc của dự án)
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-google-client-id.apps.googleusercontent.com
            client-secret: dummy-google-client-secret
            scope: profile,email
            redirect-uri: "{baseUrl}/oauth2/callback/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Xem giá trị truyền vào tham số SQL

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: core-service

application:
  security:
    jwt:
      secret-key: "mySuperSecretKeyForJwtSigningMustBeLongEnoughToSatisfyHS256Requirements"
      expiration: 86400000 # 1 day
      refresh-expiration: 604800000 # 7 days
  mail:
    from: "noreply@flashmile.local"
  frontend:
    base-url: "http://localhost:3000"
    verify-email-path: "/verify-email"
    reset-password-path: "/reset-password" # Đường dẫn frontend cho
    logo-url: https://res.cloudinary.com/dfavjndwj/image/upload/v1771167529/Vector_scx4r9.jpg
  verification:
    email-link-expiration: 900 # 15 minutes
    sms-otp-expiration: 300 # 5 minutes
    phone-verified-token-expiration: 600 # 10 minutes
    forgot-password-code-expiration: 300 # 5 minutes

springdoc:
  swagger-ui:
    try-it-out-enabled: true
