spring:
  # Testcontainers sẽ inject datasource → không cấu hình datasource tại đây

  jpa:
    hibernate:
      ddl-auto: validate # Bắt buộc khi dùng Flyway
    show-sql: false # Test không cần spam log SQL
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    clean-disabled: false # Cho phép clean trong test (tuyệt đối KHÔNG dùng ở prod)

  docker:
    compose:
      enabled: false # Test không dùng Docker Compose
  mail:
    host: localhost
    port: 1025
    test-connection: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-google-client-id.apps.googleusercontent.com
            client-secret: dummy-google-client-secret
            scope: profile,email
            redirect-uri: "{baseUrl}/oauth2/callback/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

logging:
  level:
    root: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

application:
  security:
    jwt:
      secret-key: "mySuperSecretKeyForJwtSigningMustBeLongEnoughToSatisfyHS256Requirements"
      expiration: 86400000 # 1 day
      refresh-expiration: 604800000 # 7 days
  mail:
    from: "test@flashmile.test"
  frontend:
    base-url: "http://test-frontend"
    verify-email-path: "/verify-email-test"
    reset-password-path: "/reset-password"
    logo-url: https://res.cloudinary.com/dfavjndwj/image/upload/v1771167529/Vector_scx4r9.jpg
  verification:
    email-link-expiration: 900 # 15 minutes
    sms-otp-expiration: 300 # 5 minutes
    phone-verified-token-expiration: 600 # 10 minutes
    forgot-password-code-expiration: 300 # 5 minutes
