name: Build, SonarQube Analysis Workflow, Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu" # Dùng zulu vì tối ưu cho môi trường container
          cache: "gradle"
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build, Test, and Analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew spotlessCheck clean build sonar --no-daemon --info

  deploy:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    name: Build and Push Docker Images to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: core
            deploy_url: DEPLOY_CORE_URL
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            SERVICE=${{ matrix.service }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flashmile_${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flashmile_${{ matrix.service }}:${{ github.sha }}

      - name: Wait until image is available
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          for i in {1..15}; do
            docker manifest inspect \
              "$DOCKERHUB_USERNAME/flashmile_${{ matrix.service }}:latest" \
              && exit 0
            echo "Waiting for image..."
            sleep 4
          done
          echo "Image not available"
          exit 1

      - name: Trigger deployment workflow
        env:
          DEPLOY_URL: ${{ secrets[matrix.deploy_url] }}
        run: |
          curl --fail --silent --show-error \
           --max-time 30 \
           -X POST "$DEPLOY_URL" 
